"""Fixed, reviewable reasons for QUERY_REJECTED. Free text never reaches reject()."""

from enum import StrEnum


class Reason(StrEnum):
    TABLE_RESOLUTION_MISMATCH = "table resolution does not match the query"
    DUPLICATE_BINDING = "table names and aliases must be unique"
    QUALIFIER_UNKNOWN = "a column qualifier does not match a table in the query"
    COLUMN_NOT_FOUND = "a referenced column was not found or is ambiguous"
    COLUMN_AMBIGUOUS = "a referenced column was not found or is ambiguous; qualify it"
    ORDER_OUTPUT_AMBIGUOUS = "ORDER BY refers to an ambiguous or non-column output"
    QUALIFY_FAILED = "the query references unknown or ambiguous columns"
    LIMIT_NODES = "the query exceeds the configured complexity limit"
    LIMIT_JOINS = "the query has too many joins"
    LIMIT_IN_LIST = "an IN list exceeds the configured item limit"
    TABLE_UNSUPPORTED = "only base tables of the current database are supported"
    COLUMN_REFERENCE_UNSUPPORTED = "unsupported column reference"
    COUNT_STAR_ONLY = "only COUNT(*) is supported"
    STAR_PROJECTION_ONLY = "* is supported only as a projection"
    JOIN_NEEDS_ON = "JOIN requires a table and an explicit ON expression"
    JOIN_TYPE_UNSUPPORTED = "only INNER JOIN and LEFT JOIN are supported"
    IS_NULL_ONLY = "IS is supported only with NULL"
    NEGATION_NUMERIC_ONLY = "negation is supported only for numeric literals"
    TOP_INTEGER_ONLY = "TOP/LIMIT must be a non-negative integer literal"
    ORDER_DIRECT_COLUMNS_ONLY = "ORDER BY supports only direct columns"
    IN_LITERALS_ONLY = "IN supports a column and a list of literals"
    STAR_COMPARISON = "* cannot be compared"
    SELECT_ONLY = "only SELECT statements are supported"
    PROJECTION_UNSUPPORTED = "unsupported projection"
    LIMIT_CHARS = "the SQL exceeds the configured length limit"
    ONE_STATEMENT = "exactly one statement is required"
    PARSE_FAILED = "the SQL could not be parsed"
    TOKEN_OUTSIDE_PROTECTED = "a PII token can only be compared with a protected column"
    PROTECTED_POSITION = "a protected column can only be projected or compared with a token"
    PROTECTED_NEEDS_TOKEN = "a protected column can only be compared with a PII token"
    TABLE_GONE = "a referenced table no longer exists"
    TABLE_NOT_FOUND = "a referenced table was not found or is ambiguous; qualify it with a schema"
    TABLE_SCOPE = "only tables of the current database are supported"
    BIND_UNSAFE = "bind parameters could not be generated safely"
    TOKEN_NOT_REPLACED = "a PII token could not be replaced by a bind parameter"
    NODE_UNSUPPORTED = "unsupported construct"
    OPTION_UNSUPPORTED = "unsupported option"
